

item.100= \
minecraft:lava_bucket minecraft:crimson_stem minecraft:crimson_hyphae minecraft:warped_stem minecraft:warped_hyphae minecraft:glow_lichen minecraft:small_amethyst_bud minecraft:medium_amethyst_bud minecraft:large_amethyst_bud minecraft:amethyst_cluster minecraft:glow_berries minecraft:calibrated_sculk_sensor
item.107= \
minecraft:sculk_catalyst
item.114= \
minecraft:jack_o_lantern minecraft:campfire
item.115= \
minecraft:ochre_froglight
item.117= \
minecraft:verdant_froglight
item.118= \
minecraft:sea_pickle
item.119= \
minecraft:soul_campfire
item.123= \
minecraft:pearlescent_froglight
item.125= \
minecraft:end_rod
item.126= \
minecraft:redstone_torch
item.139= \
minecraft:torch
item.144= \
minecraft:soul_torch

item.202= \
minecraft:shroomlight
item.214= \
minecraft:glowstone minecraft:lantern
item.219= \
minecraft:sea_lantern minecraft:soul_lantern
item.225= \
minecraft:beacon

item.300= \
minecraft:magma_block

item.400= \
minecraft:filled_map

#endif
